# Register-PiperRelayTask.ps1
# ---------------------------------------------------------------------------
# Make the Piper relay reboot-proof on Windows: register a per-user scheduled
# task that auto-starts the relay at logon, never times out, and restarts on
# crash (999x). The task runs a hidden VBS launcher that tees stdout+stderr to
# ~\.pi\piper\relay.log (RUST_LOG=info) so crashes are diagnosable.
#
# This script GENERATES the two launcher files (VBS + CMD) from absolute paths,
# so they are always in sync with this machine's layout — mirrors how the
# supervisor launcher is produced (plan 40). Re-run anytime to repair the task.
# No admin rights needed (user-level, InteractiveToken).
#
# Usage:   powershell -NoProfile -ExecutionPolicy Bypass -File Register-PiperRelayTask.ps1
# ---------------------------------------------------------------------------

$ErrorActionPreference = 'Stop'

# --- Paths (edit these two if the repo / install dir differ) -----------------
$piDir    = Join-Path $env:USERPROFILE '.pi\piper'                 # fork data dir
$relayDir = Join-Path $env:USERPROFILE 'source\pi\packages\remote_pi\relay'
# -----------------------------------------------------------------------------
$relayExe = Join-Path $relayDir 'target\release\relay.exe'
$logFile  = Join-Path $piDir 'relay.log'
$vbs      = Join-Path $piDir 'PiperRelayLauncher.vbs'
$cmdBat   = Join-Path $piDir 'piper-relay-run.cmd'

if (-not (Test-Path $relayExe)) { throw "relay.exe not found: $relayExe (build it first: cargo build --release in relay/)" }
New-Item -ItemType Directory -Force -Path $piDir | Out-Null

# --- Generate the CMD launcher (cd + RUST_LOG + redirect) --------------------
# cd is required: the relay resolves its SQLite path relatively ("data/mesh.db").
# RUST_LOG=info is required: tracing_subscriber::fmt emits nothing without it.
$cmdText = @"
@echo off
REM Auto-generated by Register-PiperRelayTask.ps1 - do not edit by hand.
cd /d "$relayDir"
set RUST_LOG=info
"$relayExe" >> "$logFile" 2>&1
"@
Set-Content -Path $cmdBat -Value $cmdText -Encoding ASCII

# --- Generate the VBS launcher (runs the CMD hidden, waits, propagates rc) ----
# wait=True keeps wscript alive for the relay's lifetime so RestartOnFailure
# monitors it; style 0 hides the console window.
$vbsText = @"
' Auto-generated by Register-PiperRelayTask.ps1 - do not edit by hand.
Option Explicit
Dim rc
rc = CreateObject("Wscript.Shell").Run("cmd /c ""$cmdBat""", 0, True)
WScript.Quit rc
"@
Set-Content -Path $vbs -Value $vbsText -Encoding ASCII

# --- Register the task --------------------------------------------------------
$taskName = 'Piper Relay'
$user     = "$env:USERDOMAIN\$env:USERNAME"

$action    = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument ('"{0}"' -f $vbs)
$trigger   = New-ScheduledTaskTrigger -AtLogOn -User $user
$principal = New-ScheduledTaskPrincipal -UserId $user -LogonType Interactive -RunLevel Limited
$settings  = New-ScheduledTaskSettingsSet `
              -AllowStartIfOnBatteries `
              -DontStopIfGoingOnBatteries `
              -DontStopOnIdleEnd `
              -StartWhenAvailable `
              -ExecutionTimeLimit ([TimeSpan]::Zero) `
              -RestartCount 999 `
              -RestartInterval (New-TimeSpan -Minutes 1) `
              -MultipleInstances IgnoreNew

Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger `
  -Principal $principal -Settings $settings `
  -Description 'Piper relay - auto-start at logon, restart on failure (reboot-proof)' `
  -Force | Out-Null

Write-Host "Registered '$taskName' (reboot-proof)."
Write-Host "  relay binary : $relayExe"
Write-Host "  launcher cmd : $cmdBat"
Write-Host "  launcher vbs : $vbs"
Write-Host "  log file     : $logFile"
Write-Host ""
Write-Host "Start now : schtasks /Run /TN `"Piper Relay`""
Write-Host "Stop      : schtasks /End /TN `"Piper Relay`"   (then kill any relay.exe)"
Write-Host "Status    : schtasks /Query /TN `"Piper Relay`" /V /FO LIST"
Write-Host "Logs      : Get-Content $logFile -Wait -Tail 20"
